package com.webservicex.genericBarCode;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.orasi.utils.Randomness;
import com.orasi.utils.TestEnvironment;
import com.orasi.utils.TestReporter;
import com.webservicex.genericBarCode.operations.GenerateBarCode;


public class TestGenerateBarCode extends TestEnvironment{
    @Test
    public void makeBarGenericBarCode(){
	GenerateBarCode generate = new GenerateBarCode();
	generate.sendRequest();
	TestReporter.logAPI(generate.getBarCodeBytes() != "", "Generated byte string for barcode", generate);
	generate.generateBarCodeImage();
    }

    @Test
    public void makeBarCode_FontSize(){
	GenerateBarCode generate = new GenerateBarCode();
	generate.setFontSize("14");
	generate.sendRequest();
	TestReporter.logAPI(generate.getBarCodeBytes() != "", "Generated byte string for barcode", generate);
	generate.generateBarCodeImage();
    }

    @Test
    public void makeBarCode_DisplayText(){
	GenerateBarCode generate = new GenerateBarCode();
	generate.setBarCodeText(Randomness.randomNumber(12));
	generate.sendRequest();
	TestReporter.logAPI(generate.getBarCodeBytes() != "", "Generated byte string for barcode", generate);
	generate.generateBarCodeImage();
    }

    @Test
    public void makeBarCode_DisplayPosition(){
	GenerateBarCode generate = new GenerateBarCode();
	generate.setShowTextPosition("TopCenter");
	generate.sendRequest();
	TestReporter.logAPI(generate.getBarCodeBytes() != "", "Generated byte string for barcode", generate);
	generate.generateBarCodeImage();
    }
}
